version: '3.6'
services:
    keycloak:
        image: jboss/keycloak
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
            DB_VENDOR: h2
        ports:
            - "9080:8080"