version: '3.6'
services:
    keycloak:
        build: docker
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: password
            KC_PROXY: edge
        ports:
            - "9080:8080"
        command: --http-relative-path /auth
