"/{realm}/authentication/flows" = "AuthenticationFlowRepresentation"
"/{realm}/authentication/required-actions" = "RequiredActionProviderRepresentation"
"/{realm}/authentication/unregistered-required-actions" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/clients-initial-access" = "ClientInitialAccessPresentation"
"/{realm}/groups/{id}/role-mappings/clients/{client}" = "RoleRepresentation"
"/{realm}/groups/{id}/role-mappings/clients/{client}/available" = "RoleRepresentation"
"/{realm}/groups/{id}/role-mappings/clients/{client}/composite" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/clients/{client}" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/clients/{client}/available" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/clients/{client}/composite" = "RoleRepresentation"
"/{realm}/client-scopes" = "ClientScopeRepresentation"
"/{realm}/clients" = "ClientRepresentation"
"/{realm}/clients/{id}/evaluate-scopes/protocol-mappers" = "ClientScopeEvaluateResourceProtocolMapperEvaluationRepresentation"
"/{realm}/clients/{id}/evaluate-scopes/scope-mappings/{roleContainerId}/granted" = "RoleRepresentation"
"/{realm}/clients/{id}/evaluate-scopes/scope-mappings/{roleContainerId}/not-granted" = "RoleRepresentation"
# "/{realm}/clients/{id}/offline-sessions" = "UserSessionRepresentation"
"/{realm}/clients/{id}/offline-sessions" = "HashMap<Cow<'_, str>, Value>"
# "/{realm}/clients/{id}/user-sessions" = "UserSessionRepresentation"
"/{realm}/clients/{id}/user-sessions" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/components" = "ComponentRepresentation"
"/{realm}/groups" = "GroupRepresentation"
"/{realm}/groups/{id}/members" = "UserRepresentation"
"/{realm}/identity-provider/instances" = "IdentityProviderRepresentation"
"/{realm}/identity-provider/instances/{alias}/mappers" = "IdentityProviderMapperRepresentation"
"/{realm}/client-scopes/{id}/protocol-mappers/models" = "ProtocolMapperRepresentation"
"/{realm}/client-scopes/{id}/protocol-mappers/protocol/{protocol}" = "ProtocolMapperRepresentation"
"/{realm}/clients/{id}/protocol-mappers/models" = "ProtocolMapperRepresentation"
"/{realm}/clients/{id}/protocol-mappers/protocol/{protocol}" = "ProtocolMapperRepresentation"
# "/{realm}/admin-events" = "AdminEventRepresentation"
"/{realm}/admin-events" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/client-session-stats" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/credential-registrators" = "Cow<'_, str>"
"/{realm}/default-default-client-scopes" = "ClientScopeRepresentation"
"/{realm}/default-groups" = "GroupRepresentation"
"/{realm}/default-optional-client-scopes" = "ClientScopeRepresentation"
# "/{realm}/events" = "EventRepresentation"
"/{realm}/events" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/groups/{id}/role-mappings/realm" = "RoleRepresentation"
"/{realm}/groups/{id}/role-mappings/realm/available" = "RoleRepresentation"
"/{realm}/groups/{id}/role-mappings/realm/composite" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/realm" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/realm/available" = "RoleRepresentation"
"/{realm}/users/{id}/role-mappings/realm/composite" = "RoleRepresentation"
"/{realm}/clients/{id}/roles" = "RoleRepresentation"
"/{realm}/clients/{id}/roles/{role-name}/composites" = "RoleRepresentation"
"/{realm}/clients/{id}/roles/{role-name}/composites/clients/{clientUuid}" = "RoleRepresentation"
"/{realm}/clients/{id}/roles/{role-name}/composites/realm" = "RoleRepresentation"
"/{realm}/clients/{id}/roles/{role-name}/groups" = "GroupRepresentation"
"/{realm}/clients/{id}/roles/{role-name}/users" = "UserRepresentation"
"/{realm}/roles" = "RoleRepresentation"
"/{realm}/roles/{role-name}/composites" = "RoleRepresentation"
"/{realm}/roles/{role-name}/composites/clients/{clientUuid}" = "RoleRepresentation"
"/{realm}/roles/{role-name}/composites/realm" = "RoleRepresentation"
"/{realm}/roles/{role-name}/groups" = "GroupRepresentation"
"/{realm}/roles/{role-name}/users" = "UserRepresentation"
"/{realm}/roles-by-id/{role-id}/composites" = "RoleRepresentation"
"/{realm}/roles-by-id/{role-id}/composites/clients/{clientUuid}" = "RoleRepresentation"
"/{realm}/roles-by-id/{role-id}/composites/realm" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/clients/{client}" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/clients/{client}/available" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/clients/{client}/composite" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/realm" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/realm/available" = "RoleRepresentation"
"/{realm}/client-scopes/{id}/scope-mappings/realm/composite" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/clients/{client}" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/clients/{client}/available" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/clients/{client}/composite" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/realm" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/realm/available" = "RoleRepresentation"
"/{realm}/clients/{id}/scope-mappings/realm/composite" = "RoleRepresentation"
"/{realm}/users" = "UserRepresentation"
"/{realm}/users/{id}/configured-user-storage-credential-types" = "Cow<'_, str>"
"/{realm}/users/{id}/consents" = "HashMap<Cow<'_, str>, Value>"
"/{realm}/users/{id}/credentials" = "CredentialRepresentation"
"/{realm}/users/{id}/federated-identity" = "FederatedIdentityRepresentation"
"/{realm}/users/{id}/groups" = "GroupRepresentation"
# "/{realm}/users/{id}/offline-sessions/{clientUuid}" = "UserSessionRepresentation"
"/{realm}/users/{id}/offline-sessions/{clientUuid}" = "HashMap<Cow<'_, str>, Value>"
# "/{realm}/users/{id}/sessions" = "UserSessionRepresentation"
"/{realm}/users/{id}/sessions" = "HashMap<Cow<'_, str>, Value>"
